### ISSUE TITLE
Fatal error: Duplicate keys of type 'Endpoint' were found in a Dictionary

### ISSUE THREAD

**Issue by shawnclovie** [awslabs/aws-sdk-swift#945]
### Describe the bug

In my app, I used AWS SDK to fetch files from S3 or Aliyun OSS.
On app starting, some S3 files did load to local and no issue found.
I added code like these:
```swift
class Updator {
  private let updateQueue = DispatchQueue(label: "update_apps")
  private let client: S3Client

  func update() {
    updateQueue.asyncAfter(deadline: .now() + .seconds(300)) {
      Task(priority: .background) {
         do {
           try client.listObjects(...) // or getObject, CRASH here
           // code to process files
         } catch { log error }
         self.update() // run next time
      }
```

Whole stack trace:
```
Fatal error: Duplicate keys of type 'Endpoint' were found in a Dictionary.
This usually means either that the type violates Hashable's requirements, or
that members of such a dictionary were mutated after insertion.
Current stack trace:
0    libswiftCore.so                    0x0000ffffa33acea4 _swift_stdlib_reportFatalError + 92
1    libswiftCore.so                    0x0000ffffa30caacc _assertionFailure(_:_:flags:) + 188
2    libswiftCore.so                    0x0000ffffa319d81c KEY_TYPE_OF_DICTIONARY_VIOLATES_HASHABLE_REQUIREMENTS(_:) + 604
3    libswiftCore.so                    0x0000ffffa319cf58 _NativeDictionary.resize(capacity:) + 0
4    libswiftCore.so                    0x0000ffffa3123824 _NativeDictionary.setValue(_:forKey:isUnique:) + 196
5    libswiftCore.so                    0x0000ffffa30f531c Dictionary.subscript.setter + 344
6    central_server                     0x0000aaaab4266284 <unavailable> + 21717636 // my app
7    central_server                     0x0000aaaab42672c8 <unavailable> + 21721800
8    libswift_Concurrency.so            0x0000ffffa35b2e30 <unavailable> + 273968
9    libswift_Concurrency.so            0x0000ffffa35b3650 swift_job_run + 92
10   libdispatch.so                     0x0000ffffa38babf8 <unavailable> + 175096
11   libdispatch.so                     0x0000ffffa38ba960 <unavailable> + 174432
12   libdispatch.so                     0x0000ffffa38c6c04 <unavailable> + 224260
13   libc.so.6                          0x0000ffffa288d5c8 <unavailable> + 513480
14   libc.so.6                          0x0000ffffa28f5d1c <unavailable> + 941340
```

I was print something before and after list or get, only before text printed.

If I'd batter use another way to update data with time interval, I can change it.

### Expected Behavior

Make it never crash.

### Current Behavior

Process was exit

### Reproduction Steps

In my case, the update task would run with interval 5 minutes, the app was crashed about 10+ times at yesterday night, and re-launch with supervisor.

### Possible Solution

I don't know about the crash location, I just think the actor may work to protect memory from multi-task.

### AWS SWIFT SDK version used

0.13.0

### Compiler and Version used

5.8

### Operating System and version

Ubuntu 22.04

**Comment by jbelkins** [comment]
@shawnclovie Thanks for your report.  We'll take a look & see if we can reproduce & fix the issue.  If we need more info, we'll reach out here.

**Comment by epau** [comment]
Hi @shawnclovie 
I am unable to reproduce this issue. 
Can you provide more details and more a complete code example to help debugging? 

Additionally, can you use the `listObjectsV2` operation instead of `listObjects`. The S3 service team recommends using `listObjectsV2` and only exposes `listObjects` for backwards compatibility. 

Lastly, it is not recommended to intermingle GCD with structured concurrency.  I suggest updating your code to only use structured concurrency and see if that helps fixing the issue.

Below is the code I used to attempt to reproduce this issue. 
The code will end up calling `listObjectsV2`s 6 times and it succeeds every time.

```swift
import AWSS3

class Updater {
    let client: S3Client
    var count: Int = 0
    
    init(client: S3Client) {
        self.client = client
    }
    
    func update() {
        Task.detached(priority: .background) {
            try await Task.sleep(nanoseconds: NSEC_PER_SEC * 5)
            do {
                let result = try await self.client.listObjectsV2(input: //...))
                print(result)
            } catch {
                dump(error)
            }
            self.update()
        }
    }
}

let client = try await S3Client(region: "us-east-1")
let updater = Updater(client: client)
updater.update()
try await Task.sleep(nanoseconds: NSEC_PER_SEC * 30)
```

**Comment by shawnclovie** [comment]
@epau Thank you advise! I'll update my code ASAP.

**Comment by shawnclovie** [comment]
After I updated my code - no longer use DispatchQueue, use listObjectsV2 instead.
The error still happen on Ubuntu , and it would never happen on macOS.

Here is how I create client:
```swift

struct AWSCredentialsProvider: CredentialsProvider {
	let secretID: String
	let secretKey: String

	func getCredentials() async throws -> AWSCredentials {
		AWSCredentials(accessKey: secretID, secret: secretKey, expirationTimeout: nil, sessionToken: nil)
	}
}

struct EndpointProvider: EndpointResolver {
	let endpointURL: URL
	
	func resolve(params: EndpointParams) throws -> ClientRuntime.Endpoint {
		.init(host: endpointURL.host ?? "", path: endpointURL.path,
			port: Int16(endpointURL.port ?? 443),
			protocolType: .init(rawValue: endpointURL.scheme ?? "https"))
	}
}

// either endpoint or region would be passed.
func s3client(endpoint: URL?, region: String?, secretID: String, secretKey: String) async throws {
	let credentialsProvider = AWSCredentialsProvider(secretID: secretID, secretKey: secretKey)
	let config: S3Client.S3ClientConfiguration
	if let region {
		config = try S3Client.S3ClientConfiguration(
			credentialsProvider: credentialsProvider,
			region: region)
	} else {
		config = try await S3Client.S3ClientConfiguration(
			credentialsProvider: credentialsProvider,
			endpointResolver: EndpointProvider(endpointURL: endpoint))
	}
	return .init(config: config)
}
```
I tried use `region: "ap-northeast-1"` and `endpoint: URL(string: "http://service-resources.oss-cn-shanghai.aliyuncs.com")!`.
And then I tried create client every time `update()` invoking.
But the error still happen.

**Comment by shawnclovie** [comment]
I have take another try and got some log before crash:
* Use endpoint get object from Aliyun OSS:
```json5
{"ts":"2023-04-10T13:08:15.403+08:00","level":"info","msg":"Request: GET https:443
Path: /publication/latest_version/DE0C925EB128.main
x-amz-user-agent: aws-sdk-swift/1.0,
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855,
Host: service-resources.oss-cn-shanghai.aliyuncs.com,
Authorization: AWS4-HMAC-SHA256 Credential=SECRET_ID/20230410/oss/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-user-agent, Signature=c2feccf931fb33d5e0062a25e965dd9733b64ebe4c1bbcae225988839ab4dcc7,
User-Agent: aws-sdk-swift/1.0 api/s3/1.0 os/linux lang/swift/5.8,
X-Amz-Date: 20230410T050815Z \n Optional([x-id=GetObject])","source":"Logging",
"file":"Middlewares/LoggerMiddleware.swift#32#handle(context:input:next:)"}
{"ts":"2023-04-10T13:08:15.403+08:00","level":"info",
"msg":"Creating connection pool for Optional(\"https://service-resources.oss-cn-shanghai.aliyuncs.com/publication/latest_version/DE0C925EB128.main?x-id=GetObject\")with max connections: 50","source":"Logging",
"file":"CRT/CRTClientEngine.swift#60#createConnectionPool(endpoint:)"}
Fatal error: ...
```
* Use region get object from S3:
```json5
{"ts":"2023-04-10T13:17:42.751+08:00","level":"info","msg":"Request: GET https:443
Path: /publication/latest_version/5F0C024C1985.main
Authorization: AWS4-HMAC-SHA256 Credential=SECRET_ID/20230410/ap-southeast-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-user-agent, Signature=40e3916d824f23d823de1613867f57c8bfad4aeb89a6cbea1bb9616a69108163,
x-amz-user-agent: aws-sdk-swift/1.0,
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855,
User-Agent: aws-sdk-swift/1.0 api/s3/1.0 os/linux lang/swift/5.8,
Host: es-service-resources.s3.ap-southeast-1.amazonaws.com,
X-Amz-Date: 20230410T051742Z \n Optional([x-id=GetObject])","source":"Logging",
"file":"Middlewares/LoggerMiddleware.swift#32#handle(context:input:next:)"}
{"ts":"2023-04-10T13:17:42.752+08:00","level":"info",
"msg":"Creating connection pool for Optional(\"https://es-service-resources.s3.ap-southeast-1.amazonaws.com/publication/latest_version/5F0C024C1985.main?x-id=GetObject\")with max connections: 50","source":"Logging",
"file":"CRT/CRTClientEngine.swift#60#createConnectionPool(endpoint:)"}
Fatal error: ...
```
Some \n have been replaced to newline.

**Comment by jbelkins** [comment]
While we are still not able to reproduce this crash ourselves, we have found & are correcting a bug that is related to the "Duplicate keys" error message reported above.  Fix: https://github.com/awslabs/smithy-swift/pull/548

We plan to ship this fix in the next version of the AWS SDK for Swift.  We will update on this ticket when it has been published, so you can retest and see if this fix clears your issue.

**Comment by jbelkins** [comment]
@shawnclovie We have released AWS SDK for Swift v0.15.0 with a potential fix for this crash: 
https://github.com/awslabs/aws-sdk-swift/releases/tag/0.15.0

Please update your app to this SDK version, and see if the crash continues to occur.  Thanks!

**Comment by shawnclovie** [comment]
I upgraded my app with AWS SDK 0.15.0, but crash still happened, there are same error message.
But I got more detail with gdb -
```
#0  0x0000ffff8e1faa88 in $ss17_assertionFailure__5flagss5NeverOs12StaticStringV_SSs6UInt32VtF ()
   from /opt/swift-5.8-RELEASE-ubuntu20.04-aarch64/usr/lib/swift/linux/libswiftCore.so
[Current thread is 1 (Thread 0xfffedfa89080 (LWP 1504404))]

(gdb) bt
// libswiftCore.so
#0  0x0000ffff8e1faa88 in $ss17_assertionFailure__5flagss5NeverOs12StaticStringV_SSs6UInt32VtF ()
   from /opt/swift-5.8-RELEASE-ubuntu20.04-aarch64/usr/lib/swift/linux/libswiftCore.so
#1  0x0000ffff8e2cd980 in $ss53KEY_TYPE_OF_DICTIONARY_VIOLATES_HASHABLE_REQUIREMENTSys5NeverOypXpF
    () from /opt/swift-5.8-RELEASE-ubuntu20.04-aarch64/usr/lib/swift/linux/libswiftCore.so
#2  0x0000ffff8e2538b0 in $ss17_NativeDictionaryV8setValue_6forKey8isUniqueyq_n_xSbtF ()
   from /opt/swift-5.8-RELEASE-ubuntu20.04-aarch64/usr/lib/swift/linux/libswiftCore.so
#3  0x0000ffff8e22536c in $sSDyq_Sgxcis ()
   from /opt/swift-5.8-RELEASE-ubuntu20.04-aarch64/usr/lib/swift/linux/libswiftCore.so

// in app binary
#4  0x0000aaaae0d75564 in $s13ClientRuntime15CRTClientEngineC14SerialExecutorC25getOrCreateConnectionPool8endpoint09AwsCommonB3Kit010HTTPClientJ7ManagerCAA8EndpointV_tKF ()
#5  0x0000aaaae0d765f8 in $s13ClientRuntime15CRTClientEngineC7execute7requestAA12HttpResponseCAA03SdkG7RequestC_tYaKFTY1_ ()

// libswift_Concurrency.so
#6  0x0000ffff8e7c0d1c in swift::runJobInEstablishedExecutorContext(swift::Job*) ()
   from /opt/swift-5.8-RELEASE-ubuntu20.04-aarch64/usr/lib/swift/linux/libswift_Concurrency.so
#7  0x0000ffff8e7c155c in swift_job_run ()
   from /opt/swift-5.8-RELEASE-ubuntu20.04-aarch64/usr/lib/swift/linux/libswift_Concurrency.so
#8  0x0000ffff8e9b7cd8 in _dispatch_continuation_pop ()
   from /opt/swift-5.8-RELEASE-ubuntu20.04-aarch64/usr/lib/swift/linux/libdispatch.so
#9  0x0000ffff8e9b7a40 in _dispatch_async_redirect_invoke ()
   from /opt/swift-5.8-RELEASE-ubuntu20.04-aarch64/usr/lib/swift/linux/libdispatch.so
#10 0x0000ffff8e9c408c in _dispatch_worker_thread ()
   from /opt/swift-5.8-RELEASE-ubuntu20.04-aarch64/usr/lib/swift/linux/libdispatch.so
#11 0x0000ffff8f27751c in start_thread (arg=0xfffee57e13ef) at pthread_create.c:477
#12 0x0000ffff8daeb22c in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78

```

**Comment by epau** [comment]
@shawnclovie That's unfortunate and apologies you are still having this issue. 

Would it be possible to provide us with a complete code example that reproduces this crash for you?

**Comment by shawnclovie** [comment]
@epau I'll make a repo that can reproduce the crash after I finished critical job on my hand, and then tell you here.

**Comment by shawnclovie** [comment]
I made this, and tested on Ubuntu 22, and got same error like above after 4th time update() running.
https://github.com/shawnclovie/TestVapor
@epau Could you please check it?

**Comment by jbelkins** [comment]
@shawnclovie Thanks for the test project.  I was able to reproduce the issue on Amazon Linux 2 immediately on app startup.  We will continue investigating; hopefully I can now verify for myself when the issue is actually fixed and won't have to put you through another round of testing our changes.

**Comment by jbelkins** [comment]
We have traced the cause of this crash to a bug in the Linux implementation of Foundation, namely that the Foundation type `URLQueryItem` does not properly implement the Hashable protocol on Swift for Linux.  Here is a bug ticket I filed with them:
https://github.com/apple/swift-corelibs-foundation/issues/4737

In the meantime, we are preparing a workaround for our SDK that will resolve the issue.  I ran your sample code with the workaround for about two continuous hours this afternoon with no failures, so I am confident this will solve the issue.
